### ISSUE TITLE
Support subdirs directive in stack.yaml

### ISSUE THREAD

**Issue by domenkozar** [input-output-hk/stack2nix#10]
Example: https://github.com/input-output-hk/cardano-sl-explorer/blob/master/stack.yaml#L11

Depends on #5 to avoid double-work.

**Comment by cleverca22** [comment]
in the case of `src = ../.;` based derivations, it may also improve caching to append the subdir to the src, rather then inserting it into the postUnpack, but that might have to be changed in cabal2nix

**Comment by domenkozar** [comment]
Fixed in https://github.com/input-output-hk/stack2nix/pull/36
