### ISSUE TITLE
ghcWithPackages combined with stack2nix

### ISSUE THREAD

**Issue by tfc** [input-output-hk/stack2nix#106]
Hi there,

first of all what i try to achieve:

I want `ghcid` being part of the `nix-shell` environment of my haskell projects. I do not want to force the user to install `ghcid` prior to running the nix-shell.

What i tried so far:

When i generate a `default.nix` file with `cabal2nix`, it's pretty easy to add some `.ghcWithPackages (p: [ p.ghcid ])` inbetween and have my nix shell providing `ghcid`.

Things turn out differently when i use `stack2nix` and use the compiler environment that drops out from there.

- i tried to set `compiler = pkgs.haskell.packages.ghc822.ghcWithPackages (p: [ p.ghcid ])` and then put that as the `compiler` argument into the `stackLts = import ./stack_lts_10_3.nix { inherit compiler pkgs; }` call. Then i get the error message:

```
error: anonymous function at /nix/store/2rbila6alw2l0qsmxiqgiw6kv0pdfh8p-source/pkgs/development/haskell-modules/with-packages-wrapper.nix:1:1 called with unexpected argument 'initialPackages', at /nix/store/2rbila6alw2l0qsmxiqgiw6kv0pdfh8p-source/lib/customisation.nix:74:12
```

- Then i tried to change the resulting `stackLts` object by putting `.ghcWithPackages (p: [ p.ghcid ])` on it, with the initial `compiler = pkgs.haskell.packages.ghc822` argument untouched. Then i get this error message:

```
error: attribute 'callPackage' missing, at /Users/...project folder.../default.nix:60:9
```

It seems to me that `ghcVersion.ghcWithPackages (...)` returns a derivation and that's not what works here.
But then i don't know how else to inject another package into the nix shell environment with `stack2nix` while my approach works with `cabal2nix` projects.

Is this comprehensive enough? If not, i can of course create a little example project.

**Comment by domenkozar** [comment]
Yes, I think an example would help to debug and understand what's missing.

**Comment by tfc** [comment]
Hey, i pushed a repository that contains a tiny example project and a README that documents what i did and tried so far:

https://github.com/tfc/stack2nix-with-ghcid

**Comment by domenkozar** [comment]
You need to do https://github.com/cachix/cachix/blob/master/default.nix#L18 due to #85

**Comment by tfc** [comment]
Hi Domen, thanks for pointing me to this issue, i think i added the override correctly that adds those mac dependencies into the cycle.

Unfortunately, to no avail. On mac and NixOS this works out differently:

- On mac i get some `__propagatedImpureHostDeps` missing problem
- On NixOS it's still `attribute 'callPackage' missing`

I posted the full error messages in the repository, which i refreshed together with the changes you suggested.

**Comment by domenkozar** [comment]
That's Nix specific, you'll have to play around a bit to get function calls right and macos sandboxing.

**Comment by tfc** [comment]
Hey Domen, i figured it out. Thank you very much!

I will leave that repo open, maybe it will help someone in the future.
Thank you very much for your advice!
