### ISSUE TITLE
Setup: Encountered missing dependencies: cabal2nix ==2.10.*

### ISSUE THREAD

**Issue by clacke** [input-output-hk/stack2nix#109]
Using latest nixpkgs (but shouldn't matter, because nixpkgs is pinned, right?) on Ubuntu 18.04.

Reproduce:

    $ nix-build

Expected result: stack2nix builds.

Actual result:

    Setup: Encountered missing dependencies:
    cabal2nix ==2.10.*

Noticing that `stack2nix.nix` says:

```
      "cabal2nix" = callPackage
[ . . . ]
         mkDerivation {
           pname = "cabal2nix";
           version = "2.7.2";
```

Is it out of date and should be regenerated?

**Comment by domenkozar** [comment]
This is fixed in https://github.com/input-output-hk/stack2nix/pull/108, sorry :)
