### ISSUE TITLE
Add tags for versions uploaded to hackage.

### ISSUE THREAD

**Issue by philderbeast** [input-output-hk/stack2nix#122]
There have been versions `0.1.1.0, 0.1.2.0, 0.1.3.0, 0.2` of `stack2nix` uploaded to [hackage](https://hackage.haskell.org/package/stack2nix). Could tags be added to this repository marking the source at those versions please?

**Comment by domenkozar** [comment]
I've added https://github.com/input-output-hk/stack2nix/blob/master/RELEASE.md and pinned 0.2.1, I don't want to pin those in history as I'm not sure what source was used.
