### ISSUE TITLE
Support for manually specified revisions

### ISSUE THREAD

**Issue by Infinisil** [input-output-hk/stack2nix#127]
Stack support specifying revisions of packages like this:

```yaml
- cabal-helper-0.8.1.0@rev:0
```

Apparently stack2nix can't handle this yet. I stumbled upon this when trying to upgrade [haskell-ide-engine](https://github.com/haskell/haskell-ide-engine) to the latest version for [hie-nix](https://github.com/domenkozar/hie-nix), see https://github.com/haskell/haskell-ide-engine/pull/789

My workaround for now is to manually edit the definition of the affected package in the generated nix file:
```diff
6077,6078c6077,6078
<            revision = "1";
<            editedCabalFile = "10by3n3nl6lx14asm6p8yc7bqwb4qlszf6m545jvv8scyf4nrj2g";
---
>            revision = "0";
>            editedCabalFile = "1mf041pzdhrksfbw4vianrlhm674z3p09mpbvq4kqrr9hymp3kxd";
```

**Comment by domenkozar** [comment]
See #126
