### ISSUE TITLE
stack2nix: <stdout>: commitBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/stack2nix#150]
Hi, I'm having this issue running stack2nix on a project here: https://gitlab.com/zenhaskell/rio-etc-template/-/jobs/127902000

I've played around with locales but as far as I can tell nothing's wrong.

**Comment by domenkozar** [comment]
We should probably add how to run stack2nix purely to the README.

I use:

```
nix-shell -I "nixpkgs=$nixpkgs" -p wget glibcLocales --run \
    "LANG=en_US.utf8 NIX_PATH=nixpkgs=$nixpkgs $(nix-build -A stack2nix --no-out-link)/bin/stack2nix --platform x86_64-linux --hackage-snapshot 2018-11-20T19:00:00Z . > stack2nix.nix"
```

**Comment by nh2** [comment]
Commit https://github.com/input-output-hk/stack2nix/commit/cb05818ef8b58899f15641f50cb04e5473b4f9b0 looks like it would have solved this.
