### ISSUE TITLE
pandoc 2.7 failing to build on stack2nix nightlies

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/stack2nix#157]
Hi, I don't know whether this is specifically stack2nix related but it seems very odd. Converting nightly-2019-03-06 via stack2nix and then attempting to build pandoc results in the error

```
mv: missing destination file operand after '/nix/store/4y0l42fiyn5vka6lma4s50gwygf2vfsm-pandoc-2.7/share/'
Try 'mv --help' for more information.
```

via https://gitlab.com/zenhaskell/shakebook/-/jobs/174594961

**Comment by locallycompact** [comment]
This also seems to be failing on previous stack manifests with stack2nix 0.2.2

**Comment by locallycompact** [comment]
stack2nix 0.2.2 seems to be adding this section to the pandoc derivation which is causing the failure

+           postInstall = ''
+             mkdir -p $out/share
+             mv $data/*/*/man $out/share/
+           '';

**Comment by locallycompact** [comment]
Looks like this was a known issue in cabal2nix that has now been fixed in 2.14.2, can we bump to build plan to use this? https://github.com/NixOS/cabal2nix/commit/d974819a3136486b5090e7d923fe85825e38b205

**Comment by domenkozar** [comment]
If you use nixpkgs from nixpkgs master, it should have the newest cabal2nix. Is that's where you're getting stack2nix?

**Comment by locallycompact** [comment]
Yup, tried installing stack2nix from nixos and nixpkgs unstable and it delivers the wrong pandoc command.

**Comment by domenkozar** [comment]
nixos unstable should have stack2nix that depends on cabal2nix-2.14.2.

**Comment by locallycompact** [comment]
Seems to be working now.
