### ISSUE TITLE
Don't include nixpkg's hackage-packages.nix in generated nix expression

### ISSUE THREAD

**Issue by jmitchell** [input-output-hk/stack2nix#16]
As [@bennofs points out](https://github.com/input-output-hk/stack2nix/commit/d2bb96d472e8287fb19aa6cd217ea6e1fdaedfb8#commitcomment-22426980), the generated nix expression may depend on different versions of the same package, one provided by hackage-packages.nix and the other from the generated set of mkDerivations.

We tried to get a [large project](https://github.com/input-output-hk/cardano-sl) building without hackage-packages.nix, but the trouble was `stack list-dependencies` doesn't include the full dependency closures for tests and benchmarks. We need to either:
- compute the full test/benchmark dependency closures and generate mkDerivations for them too, or
- for each dependency of the target project, strip the test dependency attributes

**Comment by domenkozar** [comment]
Stack only cares about test dependencies of packages in development, so we'll have to add support for this in cabal2nix.

**Comment by domenkozar** [comment]
I see two possible fixes upstream:

1) `peti | domenkozar: We can disable the code from https://github.com/NixOS/cabal2nix/blob/master/src/Distribution/Nixpkgs/Haskell/FromCabal.hs#L129-L136 in "fromGenericPackageDescription" based on a command line flag. That would drop all test depemndencies.`

2) Set all test dependencies as `dep ? null` for inputs, then they'd be passed forward and not used

3) Modify `callPackage` to pass null if packages don't exist (honestly this sounds like a time bomb)

**Comment by jmitchell** [comment]
In case there are any other blockers to excluding `hackage-packages.nix` I'm implementing and verifying an initial fix in stack2nix itself. Once the constraints are clearer I'll revisit making upstream changes.

On a local feature branch I successfully stripped the test and benchmark related dependencies from the expressions generated by cabal2nix. The resulting nix expression isn't building a big test project yet, but I'll investigate the new errors.
