### ISSUE TITLE
Remove hard-coded package rename map

### ISSUE THREAD

**Issue by jmitchell** [input-output-hk/stack2nix#20]
Haskell package names sometimes map to the wrong `haskellPackages.<pkg>` in nixpkgs. To ensure the generated nix expression for [cardano-sl](https://github.com/input-output-hk/cardano-sl/blob/master/stack.yaml) works, there's a [hard-coded mapping](https://github.com/input-output-hk/stack2nix/blob/master/src/Stack2nix.hs#L101-L107) from Haskell package names to the intended nixpkg name.

The hard-coded mapping should be removed and, if necessary, replaced by a CLI option so users can specify a custom name mapping that works with their target package.

To clarify why the map exists, `cardano-sl` depends on `servant` version `0.10` but in nixos 17.03 `haskellPackages.servant` corresponds to version `0.9.1.1`. However, nixpkgs also provides `haskellPackages.servant_0_10`, hence [this mapping](https://github.com/input-output-hk/stack2nix/blob/master/src/Stack2nix.hs#L104).

```
$ nix-env -f "<nixpkgs>" -qaP '.*servant.*' -A haskellPackages
...
haskellPackages.servant_0_10                   servant-0.10
haskellPackages.servant                        servant-0.9.1.1
...
```

Resolving #16 would allow us to use arbitrary package names.

**Comment by domenkozar** [comment]
Since #16 is resolved, my understanding is that this one is no longer needed?

**Comment by jmitchell** [comment]
PR #24 resolves the issue, but at the expense of being able some packages, like sevant-0.10. This is a short-term setback. Fixing requires an upstream change to [haskell-modules/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/default.nix#L25-L26) to parameterize `commonConfiguration` and `nixConfiguration`.

I'll close this after the fix is merged.
