### ISSUE TITLE
Mitigate $STACK_ROOT state problems

### ISSUE THREAD

**Issue by jmitchell** [input-output-hk/stack2nix#21]
Periodically stack2nix fails and deleting `~/.stack` seems to fix it. Typically the failure arises when stack2nix runs `stack list-dependencies`.

There are two approaches to resolving this, and doing both would be worthwhile:
1. Support and test using an isolated STACK_ROOT
2. Root cause why the old `~/.stack` state wasn't working; address as detailed reports come up

Approach 1 could optimistically use the system's current STACK_ROOT and, in case of failure, fall back to an isolated one.

**Comment by domenkozar** [comment]
This was fixed as part of #58 /cc @jmitchell
