### ISSUE TITLE
Error parsing stack.yaml file

### ISSUE THREAD

**Issue by gilligan** [input-output-hk/stack2nix#28]
I installed stack2nix 0.1.3.0:

```
nix-env -f https://github.com/NixOS/nixpkgs/tarball/8de4530b4acfcda703cac98448120aa837043983 -iA haskellPackages.stack2nix
```

I wanted to try it on some random project: https://github.com/haskell-servant/example-servant-persistent

stack.yaml:
```
resolver: lts-6.2
packages:
  - '.'
```

This fails with the following output:

```
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
stack2nix: Failed to parse ./stack.yaml
CallStack (from HasCallStack):
  error, called at src/Stack2nix.hs:158:24 in stack2nix-0.1.3.0-L6x2s4dmjRmKw75ThmpeHH:Stack2nix

```

----

Sorry if this might be something obvious. I really don't know much about stack and its config files at all.

**Comment by domenkozar** [comment]
Needs a bit more basic tests :) Currently stack2nix assumes `extra-deps` section to be in stack file.

**Comment by domenkozar** [comment]
Also a good reason to use `stack` as a library to parse the config according using their types.

**Comment by domenkozar** [comment]
Fixed in https://github.com/input-output-hk/stack2nix/pull/42, thanks for reporting!
