### ISSUE TITLE
Expose output from cabal2nix calls for dependencies with subdirs

### ISSUE THREAD

**Issue by jmitchell** [input-output-hk/stack2nix#37]
To support the `subdirs` directive in stack.yaml for non-local dependencies [this hack](https://github.com/input-output-hk/stack2nix/blob/master/src/Stack2nix.hs#L223-L224) was introduced. When there's a single dependency with multiple `subdirs` some output and retry logic gets suppressed.

**Comment by domenkozar** [comment]
This will be fixed with https://github.com/input-output-hk/stack2nix/issues/81
