### ISSUE TITLE
Linking problems whilst compiling bit-extras package (-lgcc_s)

### ISSUE THREAD

**Issue by et4te** [input-output-hk/stack2nix#40]
#Which version of nixpkgs are you supposed to use?

After doing a clone of the repo and following exact (so with the same nixpkgs generated in default.nix specified as NIX_PATH) instructions for a local package:
``error: anonymous function at /nix/store/vi96434p25iamf88ddwprpb62yqdmxry-21a8239452adae3a4717772f4e490575586b2755.tar.gz/pkgs/development/haskell-modules/default.nix:1:1 called with unexpected argument ‘configurationCommon’, at /nix/store/vi96434p25iamf88ddwprpb62yqdmxry-21a8239452adae3a4717772f4e490575586b2755.tar.gz/lib/customisation.nix:56:12``

If I change NIX_PATH to point to master:
``error: attribute ‘gcc_s’ missing, at /home/boobly/haskell/zero/default.nix:587:22
(use ‘--show-trace’ to show detailed location information)``

If I change NIX_PATH to point to unstable, same error as above.

**Comment by et4te** [comment]
The latter errors were resolved in the default derivation by changing gcc_s to point to pkgs.gcc instead of pkgs.gcc_s.

**Comment by et4te** [comment]
The failing package:
``
      bits-extras = callPackage ({ base, gcc_s, mkDerivation, stdenv }:
      mkDerivation {
          pname = "bits-extras";
          version = "0.1.3";
          sha256 = "0sy9dksmdx0773bsn8yi5hw4qpgn16g8aqqj888w1x75cbsxr997";
          isLibrary = true;
          isExecutable = true;
          libraryHaskellDepends = [
            base
          ];
          librarySystemDepends = [
            gcc_s
          ];
          doHaddock = false;
          doCheck = false;
          description = "Efficient high-level bit operations not found in Data.Bits";
          license = stdenv.lib.licenses.bsd3;
        }) { gcc_s = pkgs.gcc_s; };
``

This is how stack2nix . > foo.nix generated the dependency. pkgs.gcc_s does not exist but there is a libgcc_s.so in pkgs.gcc.cc.lib.

Adding:
``
    configureFlags = "--ghc-option=-lgcc_s --extra-lib-dirs=${gcc.cc.lib}/lib";
    librarySystemDepends = [ pkgs.gcc pkgs.gcc.cc pkgs.gcc.cc.lib ];
``

To the derivation results in a different error:

``
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `popcountll'
/nix/store/r0xlbryz4wkypgx4j3g5a3nw0k076183-base32-bytestring-0.2.1.0/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbase32-bytestring-0.2.1.0-esrbjWkQgX40VlkUUEqX3-ghc8.0.2.so: undefined reference to `bswap32'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `ctz'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `clzl'
/nix/store/r0xlbryz4wkypgx4j3g5a3nw0k076183-base32-bytestring-0.2.1.0/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbase32-bytestring-0.2.1.0-esrbjWkQgX40VlkUUEqX3-ghc8.0.2.so: undefined reference to `bswap64'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `popcountl'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `parityll'
/tmp/nix-build-bittzero-0.1.0.0.drv-0/bittzero/dist/build/libHSbittzero-0.1.0.0-EvBoYGucuMuA1t8v19ig5L-ghc8.0.2.so: undefined reference to `bittzzerozm0zi1zi0zi0zmEvBoYGucuMuA1t8v19ig5L_BittziSettings_domain_closure'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `ctzl'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `popcount'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `clz'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `parity'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `ctzll'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `parityl'
/nix/store/4jbjy0hya1m4f46zrccy8a0j8y4pcq1d-bits-extras-0.1.3/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSbits-extras-0.1.3-7YxY7d8kOvC81JvOHIFhZZ-ghc8.0.2.so: undefined reference to `clzll'
collect2: error: ld returned 1 exit status
`cc' failed in phase `Linker'. (Exit code: 1)
``

This was tested against stack lts 8.17.

**Comment by domenkozar** [comment]
This is an upstream issue for cabal2nix https://github.com/NixOS/cabal2nix/issues/71

**Comment by et4te** [comment]
Problem fixed... For anyone experiencing this issue it is caused by including redundant information in the cabal file. If e.g you include an extra dependency in an exe which is not used it can cause linking errors.

**Comment by et4te** [comment]
Managed to fix the problem by removing dependencies in the cabal file which werent being used. I had a library and executable defined and the executable didnt actually depend on bits-extras.
