### ISSUE TITLE
stack2nix: Failed to parse ./stack.yaml

### ISSUE THREAD

**Issue by Wizek** [input-output-hk/stack2nix#48]
```
$ stack2nix .
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
stack2nix: Failed to parse ./stack.yaml
CallStack (from HasCallStack):
  error, called at src/Stack2nix.hs:158:24 in stack2nix-0.1.3.0-Btpr6c9BIg88HV9cmgeSbk:Stack2nix
```

Stack seems to parse the yaml file and build the project just fine. Could it be the presence of both local and remote github `packages:` that is tripping stack2nix up? Or something else? And in either case, is there somewhere a list of features that are currently supported vs those that are upcoming?

**Comment by gilligan** [comment]
@Wizek what does the input stack.yaml look like? can you share it?

**Comment by Wizek** [comment]
@gilligan It has built up some cruft over the months, but I hope it is still helpful in this form.

Here it is: https://gist.github.com/Wizek/bec8e2b82a51c8b2feb46dba97c17698

**Comment by domenkozar** [comment]
@wizek how did you install stack2nix? What commit was used?

**Comment by Wizek** [comment]
I installed it via `nix-env -f https://github.com/NixOS/nixpkgs-channels/archive/nixpkgs-unstable.tar.gz -iA stack2nix`. I have version 0.1.3.0.

**Comment by domenkozar** [comment]
Ah yes - the released version is quite outdated. There should be a new release out soon that fixes the syack.yaml parsing, so using master branch should work.

**Comment by chris-martin** [comment]
Ping, is that release going to come?

**Comment by razvan-panda** [comment]
@domenkozar Any update on this? The version from nixpkgs is still having the issue.

**Comment by domenkozar** [comment]
@chris-martin @razvan-panda See https://github.com/input-output-hk/stack2nix/issues/94 for what's left to do.
