### ISSUE TITLE
Depend on cabal2nix as a library

### ISSUE THREAD

**Issue by domenkozar** [input-output-hk/stack2nix#5]
Currently stack2nix invokes cabal2nix via CLI interface, instead we should use Haskell API (and restrict version to minimum 2.2.1)

**Comment by domenkozar** [comment]
@jmitchell is there something prevent us doing this besides time?

**Comment by jmitchell** [comment]
If/when PR 278 in cabal2nix is accepted this should be fairly simple.

**Comment by domenkozar** [comment]
@jmitchell we could add that branch to `stack.yaml` in stack2nix repo and require stack for installation (and then #6). To release stack2nix, we'd have to wait for cabal2nix release though.

**Comment by jmitchell** [comment]
For now a runtime check of cabal2nix's version is sufficient. Using cabal2nix as a library proves difficult without making additional upstream changes.

I'll go ahead and close this, but we can revisit if there are more problems despite the runtime check.

**Comment by domenkozar** [comment]
We will still need to get this one done for #7 and #10

**Comment by domenkozar** [comment]
This should be now possible via https://hackage.haskell.org/package/cabal2nix-2.4/docs/Cabal2nix.html#v:cabal2nix-39-

**Comment by domenkozar** [comment]
This is fixed in master.
