### ISSUE TITLE
Failed to run cabal. Not found in PATH.

### ISSUE THREAD

**Issue by arianvp** [input-output-hk/stack2nix#62]
I tried installing stack2nix again, but ran into issues

```
╰─$ stack2nix .                                                             1 ↵
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
stack2nix: Failed to run cabal. Not found in PATH.
CallStack (from HasCallStack):
  error, called at src/Stack2nix.hs:72:57 in stack2nix-0.1.3.0-EmL1oxrW9vzHZqvPiu9Ocl:Stack2nix

```

Am I supposed to install cabal as well?  What I did was:

1. install stack
2. run `stack setup && stack install`
3. install `nix`
4. install cabal2nix (`nix-env -i cabal2nix`)
5. run `stack2nix .`

**Comment by arianvp** [comment]
I installed cabal with `nix-env -i cabal-install`

Running `stack2nix . ` works now without crashing, but it hangs. I cancelled the process after 3 hours

**Comment by jmitchell** [comment]
Thanks for reporting this. I updated the README to mention the runtime dependency on `cabal` via the `cabal-install` package. A while back I was trying to support a `shell.nix`, but nested `nix-shell` execution issues made me reconsider. May be worth trying again, though.

> Running `stack2nix .` works now without crashing, but it hangs.

Can you open a new issue with the repo/commit corresponding to `.` or at least what the last output was before it hanged?

**Comment by jmitchell** [comment]
@arianvp, by any chance were you on macOS? I just started testing on it and I'm seeing similar symptoms. Works fine on my NixOS box.
