### ISSUE TITLE
Using stack2nix from nix

### ISSUE THREAD

**Issue by Radivarig** [input-output-hk/stack2nix#77]
I'm trying to use stack2nix like `pkgs.haskellPackages.callCabal2nix` and when calling the binary from the build command I get
`stack2nix: cabal: readCreateProcessWithExitCode: runInteractiveProcess: chdir: does not exist (No such file or directory)`.

If I set $HOME to some folder I get `stack2nix: fd:11: hGetContents: invalid argument (invalid byte sequence)`.

This is the expression:
```nix
{ nixpkgs ? <nixpkgs> }:
let
pkgs = import nixpkgs {};
callStack2nix = name: src: ctx:
  let
  deriv = pkgs.stdenv.mkDerivation {
    inherit src;
    inherit name;
    buildInputs = [pkgs.stack2nix];
    buildCommand = ''
      HOME=/tmp/stack2nix-home
      mkdir -p $HOME
      stack2nix $src > $out
    '';
  };
  in pkgs.haskellPackages.callPackage deriv ctx;
in {
  my-package = callStack2nix "default.nix" ./. {};
}
```

**Comment by domenkozar** [comment]
stack2nix can't be used within Nix, that defeats it's purpose (it's impure).
